### ISSUE TITLE
nrf52 Feather + WebBluetooth

### ISSUE THREAD

**Issue by shtarbanov** [cadouthat/Bluetop#1]
I am just learning about webbluetooth and I  found your project. I would like to make  an LED on the nrf52 be controlled from a button on a webpage. I already found a webapp example elsehwere that does exactly that https://github.com/ketile/ketile.github.io/tree/master/physical-web/nRF-Blinky, but now I just want to also find and example of the corresponding embedded code. 

Could you please explain how in your embedded code you can read and handle the value of a custom characteristic once it has been changed? I have been looking everywhere for the hello world equivalent of Adafruit's nrf52 feather + Web-Bluetooth but I haven't found anything. There is also no explanation anywhere about the setWriteCallback() function.   Thanks.

**Comment by cadouthat** [comment]
At a high level, setWriteCallback() registers a callback function which gets called by the library/system any time the value of the characteristic is written. So you can handle any changes of the characteristic value in the callback function (e.g. write the value to a global variable to reference later, or log it to serial, or whatever you'd like to do with the value).

This is the type definition of the write callback:
`typedef void (*write_cb_t)           (BLECharacteristic& chr, uint8_t* data, uint16_t len, uint16_t offset);`

Unfortunately the details of the API don't seem to be very well documented, but based on intuition/examples these are the parameters:
chr - reference to the original BLECharacteristic that was changed
data - byte array containing the new characteristic value
len - number of bytes contained in data (the size of the characteristic value)
offset - I'm guessing this is the byte offset in data where the actual value begins, not sure when this would be non-zero, but it should definitely be checked, and presumably the value should be read starting at data[offset]
